# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-jq
  description: Process a value with a jq script and output to a step output.
  homepage: https://cloudposse.com/accelerate
  topics: ""

